# Generated by Django 3.1.3 on 2021-01-07 05:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_teams', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(2)])),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('icon', models.ImageField(upload_to='')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('wins_per', models.IntegerField()),
                ('trades', models.IntegerField(default=0)),
                ('acquisitions', models.IntegerField(default=0)),
                ('games_back', models.IntegerField(default=0)),
                ('points_for', models.IntegerField(default=0)),
                ('points_against', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('in_play', models.IntegerField()),
                ('to_play', models.IntegerField()),
                ('proj_points', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyApp.league')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasyApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('jersey_number', models.IntegerField()),
                ('avg_points', models.IntegerField()),
                ('health_status', models.CharField(max_length=100)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasyApp.team')),
            ],
        ),
    ]
